### ISSUE TITLE
Explain why there is not a 1:1 mapping

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/lake-temp-lstm-static-data-release#43]
From Sam:

> Can you explain some of the reasons why there is often not 1:1 mapping in the metadata? I thought I understood this (e.g., a lake has two big basins, and there is difference across ID systems between calling this one or two unique lakes). But, I found that hard to believe when I saw 51k LAGOS lakes didn’t have 1:1 mapping…which is something like 81% of all lakes. I was expecting this to be a smaller subset.

**Comment by jzwart** [comment]
resolved?

**Comment by lindsayplatt** [comment]
It was not yet resolved so I started looking into this. I think there may have been a misunderstanding about what is included in this file. From what I found, ~51k lakes DO have a 1:1 mapping between NHD site id and LAGOS ID:

```r
library(tidyverse)
lake_id_xwalk <- readr::read_csv('out_data/lake_id_crosswalk.csv')

# Look at only the mapping between site id and LAGOS id
lagos_to_nhd <- lake_id_xwalk %>% 
  select(site_id, LAGOS_ID) %>% 
  distinct() %>% 
  filter(!is.na(LAGOS_ID))
# A tibble: 0 × 2
# … with 2 variables: LAGOS_ID <chr>, n <int>

# How many total entries?
nrow(lagos_to_nhd)
[1] 51550

# There are no LAGOS IDs that correspond to multiple site ids
lagos_to_nhd %>% 
  group_by(LAGOS_ID) %>% 
  tally() %>% 
  filter(n > 1)

# There are no site ids that correspond to multiple LAGOS IDs.
lagos_to_nhd %>% 
  group_by(site_id) %>% 
  tally() %>% 
  filter(n > 1)
# A tibble: 0 × 2
# … with 2 variables: site_id <chr>, n <int>

# These indicate that ALL LAGOS IDs have a 1:1 mapping with site ids
```

**Comment by lindsayplatt** [comment]
The same cannot be said for MNDOW IDs, where there are examples of multiple MNDOW IDs corresponding to a single site id:

```r
mndow_to_nhd <- lake_id_xwalk %>% 
  select(site_id, MNDOW_ID) %>% 
  distinct() %>% 
  filter(!is.na(MNDOW_ID))

mndow_to_nhd %>% 
  group_by(site_id) %>% 
  tally() %>% 
  filter(n > 1) %>% 
  nrow()
[1] 326

mndow_to_nhd %>% 
  group_by(MNDOW_ID) %>% 
  tally() %>% 
  filter(n > 1) %>% 
  nrow()
[1] 0
```

**Comment by lindsayplatt** [comment]
My findings above confirm Sam's expectations that LAGOS IDs should have 1:1 mappings with site ids. I have described this behavior in the reconciliation document and I am closing this issue.
